# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Maths Refresher
author: MSc Health Data Science, LSHTM
logo: Images\logo.jpg

# Don't execute R notebooks
# See https://jupyterbook.org/content/execute.html
execute:
  exclude_patterns:
    - 'pr*'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex


# Information about where the book exists on the web
repository:
  url: https://github.com/LSHTM-HDS/Math-Refresher  # Online location of your book
  path_to_book: Refresher # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

# Configure your Binder links, such as the URL of the BinderHub.
launch_buttons:
  binderhub_url             : https://mybinder.org

exclude_patterns: [README/*]

