# Book settings

title: Maths Refresher

author: MSc Health Data Science, LSHTM
logo: Images\logo.jpg

    
targetname: book.tex

# Information about where the book exists on the web
repository:
  url                       : https://github.com/StatsFizz/Maths_Refresher
  branch                    : master  # Which branch of the repository should be used when creating links (optional)
# Configure your Binder links, such as the URL of the BinderHub.
launch_buttons:
  binderhub_url             : https://mybinder.org

exclude_patterns: [README/*]
